name: Deploy Flask App with Gunicorn

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-json-api:latest .
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-json-api:latest

            - name: Deploy to server via SSH
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      sudo docker network create npmNetwork || true

                      sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/flask-json-api:latest

                      sudo docker stop flask-json-api || true
                      sudo docker rm flask-json-api || true

                      sudo docker run -d \
                        --name flask-json-api \
                        --hostname flask-json-api \
                        --network npmNetwork \
                        ${{ secrets.DOCKER_HUB_USERNAME }}/flask-json-api:latest
